[package]
name = "ping-std"
version = "0.5.0"
edition = "2021"
authors = [
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Ulf Lilleengen <lulf@redhat.com>"
]

[dependencies]
embedded-tls = { path = "../..", features = ["log", "std", "webpki"], default-features = false }
embedded-io = { version = "0.7.1" }
embedded-io-adapters = { version = "0.7.0", features = ["std"] }
pem-parser = "0.1"
env_logger = "0.11.11"
rand = "0.10.2"
log = "0.4"
aes-gcm = "0.11.1"
hmac = "0.13"
sha2 = "0.11"
p256 = { version = "0.14", default-features = false, features = ["ecdsa"] }
