[package]
name = "ping-embassy-net"
version = "0.5.0"
edition = "2021"
resolver = "2"

[dependencies]
embedded-tls = { path = "../..", features = ["alloc", "std", "log"], default-features = false }
env_logger = "0.11.11"
rand = "0.10.2"
log = "0.4"
static_cell = "2.1.1"
embassy-executor = { version = "0.10.0", features = ["platform-std", "executor-thread", "executor-thread", "log"] }
embassy-time = { version = "0.5.1", default-features = false, features = ["std"] }
smoltcp = { version = "0.14.0", features = ["dns-max-server-count-4"] }
embassy-net = { version = "0.9.1", features=[ "std", "log", "medium-ethernet", "medium-ip", "tcp", "udp", "dns", "dhcpv4", "proto-ipv6"] }
embassy-net-tuntap = { version = "0.1.1" }

async-io = "2.6.0"
futures = { version = "0.3.34" }
libc = "0.2.189"
clap = { version = "4.6.6", features = ["derive", "color"] }
heapless = { version = "0.9.3", default-features = false }
embedded-io-async = { version = "0.7" }
embedded-io-adapters = { version = "0.7", features = ["futures-03"] }
critical-section = { version = "1.2.0", features = ["std"] }
