[package]
name = "tls-server-blocking"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-tls = { path = "../..", features = ["log", "x25519"] }
embedded-io = "0.7"
embedded-io-adapters = { version = "0.7", features = ["std"] }
env_logger = "0.10"
rand = "0.8"
rand_core = "0.6"
log = "0.4"
p256 = { version = "0.13", features = ["ecdsa"] }
ecdsa = "0.16"
signature = "2"
rustls-pemfile = "1"
