name: CI

on:
  push:
    # Run on the main branch
    branches:
      - main
    # Releases are tags named 'v<version>', and must have the "major.minor.micro", for example: "0.1.0".
    # Release candidates are tagged as `v<version>-rc<num>`, for example: "0.1.0-rc1".
    tags:
      - "v*"
  # Also on PRs, just be careful not to publish anything
  pull_request:

jobs:
  library-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subcmd: [build, clippy, test]

    steps:
      - uses: actions/checkout@v4

      - name: Run `cargo ${{ matrix.subcmd }}` for library
        run: cargo ${{ matrix.subcmd }} --features webpki

  example-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [embassy, blocking, tokio, tokio-psk]

    steps:
      - uses: actions/checkout@v4

      - name: Run `cargo build` for example ${{ matrix.example }}
        working-directory: examples/${{ matrix.example }}
        run: cargo build
